import {

  DashboardGrid,
  DashboardSection,

  BaseCard,
  ExecutiveCard,
  MetricCard,
  StatusBadge,

} from "@/components/ui";

import {

  Brain,
  Lightbulb,
  Sparkles,

} from "@/components/ui";

import type {

  AdvisorIntelligence,

} from "@/types/advisor";

interface RepositoryAdvisorDashboardProps {

  advisor: AdvisorIntelligence;

}

export function RepositoryAdvisorDashboard({

  advisor,

}: RepositoryAdvisorDashboardProps) {

  return (

    <DashboardSection

      title="AI Engineering Advisor"

      description="Engineering recommendations generated from portfolio execution intelligence."

    >

      <DashboardGrid columns={2}>

        <MetricCard

          title="AI Insights"

          value={advisor.insights.length}

          icon={
            <Brain
              className="h-6 w-6 text-cyan-400"
            />
          }

        />

        <MetricCard

          title="Advisor Confidence"

          value={advisor.summary.confidence}

          suffix="%"

          precision={1}

          icon={
            <Sparkles
              className="h-6 w-6 text-amber-400"
            />
          }

        />

      </DashboardGrid>

      <ExecutiveCard

        title="Executive Narrative"

        summary={
          advisor.summary.executiveNarrative
        }

      />
      <DashboardSection

  title="Engineering Recommendations"

  description="Actionable recommendations generated by the AI Engineering Advisor."

>

  <div className="space-y-4">

    {advisor.insights.map((insight) => (

      <BaseCard

        key={insight.title}

        title={insight.title}

        variant="default"

      >

        <div className="space-y-4">

          <p className="text-sm text-zinc-300">

            {insight.summary}

          </p>

          <DashboardGrid columns={2}>

            <StatusBadge

              variant={
                insight.severity === "Critical"
                  ? "danger"
                  : insight.severity === "Warning"
                  ? "warning"
                  : insight.severity === "Recommendation"
                  ? "info"
                  : "neutral"
              }

            >

              {insight.severity}

            </StatusBadge>

            <StatusBadge

              variant="info"

            >

              {insight.category}

            </StatusBadge>

          </DashboardGrid>

        </div>

      </BaseCard>

    ))}

  </div>

</DashboardSection>

    </DashboardSection>

  );

}