"use client";

import {
    useEffect,
    useState,
    useSyncExternalStore,
} from "react";


import {
    FileText,
    X,
} from "lucide-react";

import type {
    IntelligenceArtifact,
    IntelligenceArtifactTrustAssessment,
} from "@/types/intelligence";

import {
    IntelligenceArtifactLineage,
} from "./IntelligenceArtifactLineage";

import {
    IntelligenceArtifactStatusBadge,
} from "./IntelligenceArtifactStatusBadge";

import {
    IntelligenceArtifactExportButtons,
} from "./IntelligenceArtifactExportButtons";

import {
    IntelligenceArtifactIntegrity,
} from "./IntelligenceArtifactIntegrity";

import {
    IntelligenceArtifactTrust,
} from "./IntelligenceArtifactTrust";

import {
    IntelligenceArtifactSigningPanel,
} from "./IntelligenceArtifactSigningPanel";

import {
    assessArtifactTrust,
} from "@/lib/intelligence/artifactTrustService";

import {
    archiveIntelligenceArtifact,
    publishIntelligenceArtifact,
    supersedeIntelligenceArtifact,
    getAllowedArtifactStatusTransitions,
    subscribeToIntelligenceArtifacts,
    getArtifactFamily,
    getIntelligenceArtifacts,
} from "@/lib/intelligence/artifactRegistry";





const EMPTY_ARTIFACTS:
    IntelligenceArtifact[] = [];

function getArtifactsSnapshot():
    IntelligenceArtifact[] {
    return getIntelligenceArtifacts();
}

function getServerSnapshot():
    IntelligenceArtifact[] {
    return EMPTY_ARTIFACTS;
}

export function IntelligenceArtifactHistory() {
    const artifacts =
        useSyncExternalStore(
            subscribeToIntelligenceArtifacts,
            getArtifactsSnapshot,
            getServerSnapshot,
        );

    const [
        selectedArtifact,
        setSelectedArtifact,
    ] =
        useState<IntelligenceArtifact | null>(
            null,
        );

    if (
        artifacts.length === 0
    ) {
        return (
            <section className="mt-10 rounded-3xl border border-white/10 bg-white/[0.02] p-6">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">
                    Intelligence Artifacts
                </p>

                <h3 className="mt-2 text-xl font-bold text-white">
                    No artifacts registered yet
                </h3>

                <p className="mt-2 text-sm leading-6 text-zinc-500">
                    Reports and other intelligence
                    deliverables registered from this
                    browser will appear here.
                </p>
            </section>
        );
    }

    return (
        <>
            <section className="mt-10">
                <div className="mb-4">
                    <p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">
                        Intelligence Artifacts
                    </p>

                    <h3 className="mt-2 text-2xl font-black text-white">
                        Artifact Registry
                    </h3>

                    <p className="mt-2 text-sm text-zinc-500">
                        Registered intelligence deliverables
                        generated by TITAN.
                    </p>
                </div>

                <div className="grid gap-4">
                    {artifacts.map(
                        (artifact) => (
                            <button
                                key={
                                    artifact.artifactId
                                }
                                type="button"
                                onClick={() =>
                                    setSelectedArtifact(
                                        artifact,
                                    )
                                }
                                className="w-full rounded-2xl border border-white/10 bg-white/[0.02] p-5 text-left transition hover:border-cyan-400/30 hover:bg-cyan-400/[0.03]"
                            >
                                <div className="flex items-start justify-between gap-4">
                                    <div className="flex items-start gap-3">
                                        <div className="rounded-xl border border-white/10 bg-white/[0.03] p-2">
                                            <FileText className="h-5 w-5 text-cyan-400" />
                                        </div>

                                        <div>
                                            <p className="font-semibold text-white">
                                                {artifact.metadata
                                                    .title ??
                                                    artifact.artifactType}
                                            </p>

                                            <p className="mt-1 text-sm text-zinc-500">
                                                {
                                                    artifact.repository
                                                }
                                            </p>
                                        </div>
                                    </div>

                                    <div className="flex shrink-0 flex-wrap items-center justify-end gap-2">
                                        <span className="rounded-full border border-white/10 px-2.5 py-1 text-xs font-semibold text-zinc-400">
                                            v
                                            {
                                                artifact.version
                                            }
                                        </span>

                                        <IntelligenceArtifactStatusBadge
                                            status={
                                                artifact.status
                                            }
                                        />
                                    </div>
                                </div>

                                <div className="mt-4 grid gap-3 text-xs text-zinc-500 sm:grid-cols-3">
                                    <span>
                                        Type:{" "}
                                        {
                                            artifact.artifactType
                                        }
                                    </span>

                                    <span>
                                        Format:{" "}
                                        {
                                            artifact.format
                                        }
                                    </span>

                                    <span>
                                        Author:{" "}
                                        {
                                            artifact.author
                                        }
                                    </span>
                                </div>
                            </button>
                        ),
                    )}
                </div>
            </section>

            {selectedArtifact ? (
                <ArtifactDetails
                    artifact={
                        selectedArtifact
                    }
                    onClose={() =>
                        setSelectedArtifact(null)
                    }
                    onArtifactSigned={
                        setSelectedArtifact
                    }
                />
            ) : null}
        </>
    );
}
/* -------------------------------------------------------------------------- */
/*                         Artifact Lifecycle Controls                         */
/* -------------------------------------------------------------------------- */

function ArtifactLifecycleControls({
    artifact,
    onUpdated,
}: {
    artifact: IntelligenceArtifact;
    onUpdated: (
        artifact: IntelligenceArtifact,
    ) => void;
}) {
    const status =
        artifact.status ??
        "Registered";

    const allowedTransitions =
        getAllowedArtifactStatusTransitions(
            status,
        );

    function transition(
        nextStatus: IntelligenceArtifact["status"],
    ) {
        if (!nextStatus) {
            return;
        }

        let updated:
            IntelligenceArtifact | null =
            null;

        if (
            nextStatus ===
            "Published"
        ) {
            updated =
                publishIntelligenceArtifact(
                    artifact.artifactId,
                );
        }

        if (
            nextStatus ===
            "Superseded"
        ) {
            updated =
                supersedeIntelligenceArtifact(
                    artifact.artifactId,
                );
        }

        if (
            nextStatus ===
            "Archived"
        ) {
            updated =
                archiveIntelligenceArtifact(
                    artifact.artifactId,
                );
        }

        if (updated) {
            onUpdated(updated);
        }
    }

    return (
        <section className="mt-6 rounded-2xl border border-white/10 bg-white/[0.02] p-4">
            <div className="flex items-center justify-between gap-4">
                <div>
                    <p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">
                        Lifecycle
                    </p>

                    <p className="mt-1 text-sm text-zinc-500">
                        Controlled artifact state
                        transitions.
                    </p>
                </div>

                <IntelligenceArtifactStatusBadge
                    status={
                        artifact.status
                    }
                />
            </div>

            {allowedTransitions.length >
            0 ? (
                <div className="mt-4 flex flex-wrap gap-2">
                    {allowedTransitions.map(
                        (
                            nextStatus,
                        ) => {
                            if (
                                nextStatus ===
                                "Registered"
                            ) {
                                return null;
                            }

                            return (
                                <button
                                    key={
                                        nextStatus
                                    }
                                    type="button"
                                    onClick={() =>
                                        transition(
                                            nextStatus,
                                        )
                                    }
                                    className="rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2 text-xs font-semibold text-zinc-300 transition hover:border-cyan-400/30 hover:bg-cyan-400/[0.05] hover:text-white"
                                >
                                    {nextStatus}
                                </button>
                            );
                        },
                    )}
                </div>
            ) : (
                <p className="mt-4 text-xs text-zinc-600">
                    No further lifecycle
                    transitions are available.
                </p>
            )}
        </section>
    );
}
/* -------------------------------------------------------------------------- */
/*                         Artifact Details                                   */
/* -------------------------------------------------------------------------- */

interface ArtifactDetailsProps {
    artifact: IntelligenceArtifact;
    onClose: () => void;
    onArtifactSigned: (
        artifact: IntelligenceArtifact,
    ) => void;
}

function ArtifactDetails({
    artifact,
    onClose,
    onArtifactSigned,
}: ArtifactDetailsProps) {
    const lineage =
        getArtifactFamily(
            artifact.artifactId,
        );
    const [
        trustAssessment,
        setTrustAssessment,
    ] =
        useState<
            IntelligenceArtifactTrustAssessment | null
        >(null);
    useEffect(() => {
        let cancelled = false;

        async function evaluateTrust() {
            try {
                const assessment =
                    await assessArtifactTrust(
                        artifact,
                    );

                if (!cancelled) {
                    setTrustAssessment(
                        assessment,
                    );
                }
            } catch (error) {
                console.error(
                    "Failed to assess artifact trust:",
                    error,
                );

                if (!cancelled) {
                    setTrustAssessment(
                        null,
                    );
                }
            }
        }

        void evaluateTrust();

        return () => {
            cancelled = true;
        };
    }, [artifact]);


    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm">
            <section className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-white/10 bg-zinc-950 p-6 shadow-2xl">
                <div className="flex items-start justify-between gap-4">
                    <div>
                        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">
                            Intelligence Artifact
                        </p>

                        <h3 className="mt-2 text-2xl font-black text-white">
                            {artifact.metadata
                                .title ??
                                artifact.artifactType}
                        </h3>
                    </div>

                    <button
                        type="button"
                        onClick={onClose}
                        aria-label="Close artifact"
                        className="rounded-xl border border-white/10 p-2 text-zinc-500 transition hover:bg-white/[0.05] hover:text-white"
                    >
                        <X className="h-4 w-4" />
                    </button>
                </div>

                {/* ------------------------------------------------------------------ */}
                {/* Artifact Metadata                                                  */}
                {/* ------------------------------------------------------------------ */}

                <div className="mt-6 grid gap-4 sm:grid-cols-2">
                    <ArtifactField
                        label="Artifact ID"
                        value={
                            artifact.artifactId
                        }
                    />

                    <ArtifactField
                        label="Type"
                        value={
                            artifact.artifactType
                        }
                    />

                    <ArtifactField
                        label="Repository"
                        value={
                            artifact.repository
                        }
                    />

                    <ArtifactField
                        label="Version"
                        value={
                            artifact.version
                        }
                    />

                    <ArtifactField
                        label="Format"
                        value={
                            artifact.format
                        }
                    />

                    <ArtifactField
                        label="Status"
                        value={
                            artifact.status
                        }
                    />

                    <ArtifactField
                        label="Author"
                        value={
                            artifact.author
                        }
                    />

                    <ArtifactField
                        label="Source"
                        value={
                            artifact.source
                        }
                    />

                    <ArtifactField
                        label="Source Snapshot"
                        value={
                            artifact.sourceSnapshotId
                        }
                    />

                    <ArtifactField
                        label="Created"
                        value={
                            artifact.createdAt
                        }
                    />

                    <ArtifactField
                        label="Generated"
                        value={
                            artifact.generatedAt
                        }
                    />

                    {artifact.previousArtifactId ? (
                        <ArtifactField
                            label="Previous Artifact"
                            value={
                                artifact.previousArtifactId
                            }
                        />
                    ) : null}
                </div>

                <div className="mt-6">
                    <ArtifactLifecycleControls
                        artifact={artifact}
                        onUpdated={onArtifactSigned}
                    />
                </div>
                {/* ------------------------------------------------------------------ */}
                {/* Artifact Lineage                                                   */}
                {/* ------------------------------------------------------------------ */}

                <IntelligenceArtifactLineage
                    artifacts={lineage}
                    currentArtifactId={
                        artifact.artifactId
                    }
                />

                <IntelligenceArtifactExportButtons
                    artifactId={
                        artifact.artifactId
                    }
                />
                <IntelligenceArtifactIntegrity
                    artifactId={
                        artifact.artifactId
                    }
                    hasIntegrity={
                        Boolean(
                            artifact.integrity,
                        )
                    }
                    hash={
                        artifact.integrity?.hash
                    }
                />
                <IntelligenceArtifactSigningPanel
                    artifact={artifact}
                    onSigned={onArtifactSigned}
                />
                {trustAssessment ? (
                    <IntelligenceArtifactTrust
                        assessment={
                            trustAssessment
                        }
                        signerName={
                            artifact.signature
                                ?.signerName
                        }
                        signerId={
                            artifact.signature
                                ?.signerId
                        }
                        signedAt={
                            artifact.signature
                                ?.signedAt
                        }
                    />
                ) : (
                    <section className="mt-6 rounded-2xl border border-white/10 bg-white/[0.02] p-4">
                        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">
                            Trust
                        </p>

                        <p className="mt-2 text-sm text-zinc-500">
                            Evaluating artifact trust...
                        </p>
                    </section>
                )}

                {/* ------------------------------------------------------------------ */}
                {/* Description                                                        */}
                {/* ------------------------------------------------------------------ */}

                {artifact.metadata
                    .description ? (
                    <div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.02] p-4">
                        <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">
                            Description
                        </p>

                        <p className="mt-2 text-sm leading-6 text-zinc-300">
                            {
                                artifact.metadata
                                    .description
                            }
                        </p>
                    </div>
                ) : null}

                {/* ------------------------------------------------------------------ */}
                {/* Tags                                                               */}
                {/* ------------------------------------------------------------------ */}

                {artifact.metadata.tags
                    ?.length ? (
                    <div className="mt-4 flex flex-wrap gap-2">
                        {artifact.metadata.tags.map(
                            (tag) => (
                                <span
                                    key={tag}
                                    className="rounded-full border border-white/10 px-3 py-1 text-xs text-zinc-400"
                                >
                                    {tag}
                                </span>
                            ),
                        )}
                    </div>
                ) : null}
            </section>
        </div>
    );
}

/* -------------------------------------------------------------------------- */
/*                         Artifact Field                                     */
/* -------------------------------------------------------------------------- */

interface ArtifactFieldProps {
    label: string;
    value: string;
}

function ArtifactField({
    label,
    value,
}: ArtifactFieldProps) {
    return (
        <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">
                {label}
            </p>

            <p className="mt-2 break-words text-sm font-semibold text-zinc-200">
                {value}
            </p>
        </div>
    );
}
